# Generated by Django 5.1.14 on 2025-11-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_api_a_target__4f314e_idx',
            old_name='admin_api_target_idx',
        ),
    ]
