# Generated by Django 5.1.14 on 2025-11-08 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsredemption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
